### ISSUE TITLE
Upgrade peer dependencies from Angular 6 to 7

### ISSUE THREAD

**Issue by rafa-as** [muratcorlu/ngx-script-loader#11]
Upgrade peer Angular dependencies to avoid the following warnings:

```
warning ngx-script-loader@1.0.0" has incorrect peer dependency "@angular/common@^6.0.0-rc.0 || ^6.0.0".
warning ngx-script-loader@1.0.0" has incorrect peer dependency "@angular/core@^6.0.0-rc.0 || ^6.0.0".
```

**Comment by muratcorlu** [comment]
But I didn't check library at v7 yet. Can you also check if it's working properly? I don't expect any problem but we need to check anyway

**Comment by rafa-as** [comment]
Yes for sure, we are using with Angular 7 + SSR without any problem :)

**Comment by muratcorlu** [comment]
Merged. Thank you. I'll create a release with that. I think a minor version will be enough, right?

**Comment by rafa-as** [comment]
Yes, totally agree.

**Comment by muratcorlu** [comment]
Release as 1.1.0 https://www.npmjs.com/package/ngx-script-loader

**Comment by rafa-as** [comment]
Thank you @muratcorlu
