### ISSUE TITLE
Remove script feature

### ISSUE THREAD

**Issue by MurhafSousli** [muratcorlu/ngx-script-loader#13]
Hi, I want to destroy a script on component destroy, is it possible to remove a script after it is loaded?

**Comment by muratcorlu** [comment]
Removing script tag from document will not disable the code that we already injected. I don't know any way to really clean JS code from document after it's run once.

**Comment by MurhafSousli** [comment]
Yea, that's right, the script can be remove using `event.target.remove()` but the problem is with cleaning up!
