### ISSUE TITLE
Reloading of scripts fails when the service is injected

### ISSUE THREAD

**Issue by matthiasbaldi** [muratcorlu/ngx-script-loader#14]
I use your component to load a script which is bring a social media feed on my page.
In my application I had the issue, that your component was working properly as long the `news component` was just visited once. Otherwise the scriptService was not reloading the script and the `div` in the template was still empty.

So as soon I have not injected the service in the constructor but created a new service instance manually, it worked.
My solution:

```
export class NewsComponent implements OnInit {

    @ViewChild('scriptPlaceholder') element: ElementRef;

    public elAttr: any = {
        'data-attr-list': 'data'
    };

    constructor() { }

    ngOnInit() {
        let scriptService: ScriptService = new ScriptService(document);
        scriptService.loadScript('https://myscript.io/blah.js', this.elAttr, this.element.nativeElement)
            .subscribe();
    }
}
```

What do you think? Is this an issue/bug? Or is this an expected behavior?
Thank you.

**Comment by muratcorlu** [comment]
I see the problem. There is a cache mechanism in `ScriptService` to not load same js file multiple times. I thought, importing a file to a document once should be enough most of the cases. But in your case, probably your js resource is doing some stuff when it's first running. So you need to inject it again to run it again. 

In your solution, you are bypassing this in-memory cache mechanism by creating a new instance every time. I don't think that approach will cause a problem but maybe there should be a better solution in library.

**Comment by AXeL-dev** [comment]
I think that adding a `bypassCache` or `forceLoad` parameter to loadScript function would be better :thinking:

**Comment by muratcorlu** [comment]
What about having another method for this, like `runScript()`? So if you want to just load an external library once(as usual) you'll just continue to use `loadScript()`. But if you want to *run* the external code even if it was already run before, then use `runScript()`.

Is this a better/practical idea?

Because for now we don't have a configuration parameter on `loadScript()`. Adding another parameter for it will be more complicated, I think.

**Comment by matthiasbaldi** [comment]
@muratcorlu 
That sounds good. Would help and separate the different "topics" into two methods.
For that there would be needed to extend the `script.service.ts` and may to move out the main part into a private method.

**Comment by muratcorlu** [comment]
I added `runScript` method with this commit: https://github.com/muratcorlu/ngx-script-loader/commit/359bc83ba4c721039a706875f2af5b8b4b2ba2b3

Deployed with v1.3.0

**Comment by matthiasbaldi** [comment]
ty, I will test it asap.

**Comment by matthiasbaldi** [comment]
sry could not test earlier, works as expected. Ty for your work and this fix! 👍
