### ISSUE TITLE
Angular 6 support?

### ISSUE THREAD

**Issue by maxisam** [muratcorlu/ngx-script-loader#2]
Any plan for angular 6 support?

**Comment by muratcorlu** [comment]
Let me check what we need. I think it will be not so hard.

**Comment by maxisam** [comment]
not much. just 
for service.ts, you need to use pipe operator

import { Injectable, Inject } from '@angular/core';
import { Observable } from 'rxjs';
import { take, shareReplay } from 'rxjs/operators';
import { DOCUMENT } from '@angular/common';

and you can get rid of declaring document part with
```
  constructor(@Inject(DOCUMENT) private _Document: any) {}
```

use `new Observable` instead of `observable.create`

Honestly, if you can upgrade the project by using angular 6 cli to generate it. I can help you update the rest of the code.

**Comment by muratcorlu** [comment]
https://github.com/muratcorlu/ngx-script-loader/tree/angular-6

I'll test this and merge/publish as soon as possible.

**Comment by muratcorlu** [comment]
It's merged and publish with version 0.3.0. It should be usable with angular 6 now. https://www.npmjs.com/package/ngx-script-loader/v/0.3.0

btw: somehow npm couldn't read the readme document. Do you have any idea?

**Comment by maxisam** [comment]
I think you need to have a copy of readme in the project folder [here](https://github.com/muratcorlu/ngx-script-loader/tree/master/projects/ngx-script-loader)

Or you can have a task to copy the readme file from root folder to dist/project folder.

like having this in your npm task and chain them by && with your build task
`copy-readme: "cpx \"./readme.md\" \"./dist/mylib\"",`


IMHO, the version number should be 1.0.0, since there is a breaking change in this update

**Comment by muratcorlu** [comment]
OK, I'll publish v1.0 after waiting pull-requests. Thanks for your help!

**Comment by dramentol** [comment]
Angular 5 support?
