### ISSUE TITLE
Support for Ivy compilation (Angular 13 and newer)

### ISSUE THREAD

**Issue by inorganik** [muratcorlu/ngx-script-loader#65]
When compiling an angular app in version 13 or newer, you'll see warnings for libs that require ngcc for compilation. In the case of ngx script loader, it looks like this:

```
- ngx-script-loader [es2015/esm2015] (git+https://github.com/muratcorlu/ngx-script-loader.git)
Encourage the library authors to publish an Ivy distribution.
```

It should be as simple as upgrading the repo to ng 13 or newer, and re-publishing. I maintain and angular lib, here is the PR that made this change if you are interested: https://github.com/inorganik/ngx-countUp/pull/68

**Comment by muratcorlu** [comment]
Fixed with #72 and released by https://github.com/muratcorlu/ngx-script-loader/releases/tag/v3.0.0
